repos:
  - repo: local
    hooks:
      - id: nbstripout-fast
        name: nbstripout-fast
        entry: nbstripout-fast
        language: system
        files: \.ipynb$

      - id: black
        name: black
        entry: black
        language: system
        types_or: [python, pyi, jupyter]
        
      - id: isort
        name: isort (python)
        entry: isort
        language: system
        types: [python]
